BEGIN;

CREATE TABLE IF NOT EXISTS unicarona.conversas (
  id_conversa INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_solicitacao INTEGER NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT conversas_pkey PRIMARY KEY (id_conversa),
  CONSTRAINT uq_conversas_solicitacao UNIQUE (id_solicitacao),
  CONSTRAINT fk_conversas_solicitacoes
    FOREIGN KEY (id_solicitacao)
    REFERENCES unicarona.solicitacoes(id_solicitacao)
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS unicarona.mensagens (
  id_mensagem INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_conversa INTEGER NOT NULL,
  id_remetente INTEGER NOT NULL,
  conteudo VARCHAR(1000) NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT mensagens_pkey PRIMARY KEY (id_mensagem),
  CONSTRAINT chk_mensagens_conteudo
    CHECK (LENGTH(BTRIM(conteudo)) BETWEEN 1 AND 1000),
  CONSTRAINT fk_mensagens_conversas
    FOREIGN KEY (id_conversa)
    REFERENCES unicarona.conversas(id_conversa)
    ON DELETE RESTRICT,
  CONSTRAINT fk_mensagens_remetente
    FOREIGN KEY (id_remetente)
    REFERENCES unicarona.usuarios(id_usuario)
    ON DELETE RESTRICT
);

INSERT INTO unicarona.conversas (id_solicitacao)
SELECT id_solicitacao
FROM unicarona.solicitacoes
WHERE status = 'ACEITA'
ON CONFLICT (id_solicitacao) DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_mensagens_conversa_criado_em
  ON unicarona.mensagens (id_conversa, criado_em);

REVOKE ALL ON unicarona.conversas, unicarona.mensagens
  FROM PUBLIC, anon, authenticated;

REVOKE ALL ON SEQUENCE unicarona.conversas_id_conversa_seq,
  unicarona.mensagens_id_mensagem_seq
  FROM PUBLIC, anon, authenticated;

COMMIT;
