BEGIN;

CREATE TABLE IF NOT EXISTS unicarona.conversas (
  id_conversa INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_solicitacao INTEGER NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT conversas_pkey PRIMARY KEY (id_conversa),
  CONSTRAINT uq_conversas_solicitacao UNIQUE (id_solicitacao),
  CONSTRAINT fk_conversas_solicitacoes
    FOREIGN KEY (id_solicitacao)
    REFERENCES unicarona.solicitacoes(id_solicitacao)
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS unicarona.mensagens (
  id_mensagem INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_conversa INTEGER NOT NULL,
  id_remetente INTEGER NOT NULL,
  conteudo VARCHAR(1000) NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT mensagens_pkey PRIMARY KEY (id_mensagem),
  CONSTRAINT chk_mensagens_conteudo
    CHECK (LENGTH(BTRIM(conteudo)) BETWEEN 1 AND 1000),
  CONSTRAINT fk_mensagens_conversas
    FOREIGN KEY (id_conversa)
    REFERENCES unicarona.conversas(id_conversa)
    ON DELETE RESTRICT,
  CONSTRAINT fk_mensagens_remetente
    FOREIGN KEY (id_remetente)
    REFERENCES unicarona.usuarios(id_usuario)
    ON DELETE RESTRICT
);

INSERT INTO unicarona.conversas (id_solicitacao)
SELECT id_solicitacao
FROM unicarona.solicitacoes
WHERE status = 'ACEITA'
ON CONFLICT (id_solicitacao) DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_mensagens_conversa_criado_em
  ON unicarona.mensagens (id_conversa, criado_em);

CREATE OR REPLACE FUNCTION unicarona.usuario_participa_conversa(topico TEXT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM unicarona.conversas conversa
    INNER JOIN unicarona.solicitacoes solicitacao
      ON solicitacao.id_solicitacao = conversa.id_solicitacao
    INNER JOIN unicarona.caronas carona
      ON carona.id_carona = solicitacao.id_carona
    INNER JOIN unicarona.usuarios passageiro
      ON passageiro.id_usuario = solicitacao.id_passageiro
    INNER JOIN unicarona.usuarios motorista
      ON motorista.id_usuario = carona.id_usuario
    WHERE topico = 'conversa:' || conversa.id_conversa::TEXT
      AND (
        passageiro.auth_id = (SELECT auth.uid())
        OR motorista.auth_id = (SELECT auth.uid())
      )
  );
$$;

REVOKE ALL ON FUNCTION unicarona.usuario_participa_conversa(TEXT)
  FROM PUBLIC;
GRANT EXECUTE ON FUNCTION unicarona.usuario_participa_conversa(TEXT)
  TO authenticated;

DROP POLICY IF EXISTS chat_participantes_recebem_mensagens
  ON realtime.messages;

CREATE POLICY chat_participantes_recebem_mensagens
  ON realtime.messages
  FOR SELECT
  TO authenticated
  USING (
    realtime.messages.extension = 'broadcast'
    AND unicarona.usuario_participa_conversa(
      (SELECT realtime.topic())
    )
  );

CREATE OR REPLACE FUNCTION unicarona.notificar_nova_mensagem()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  PERFORM realtime.broadcast_changes(
    'conversa:' || NEW.id_conversa::TEXT,
    TG_OP,
    TG_OP,
    TG_TABLE_NAME,
    TG_TABLE_SCHEMA,
    NEW,
    OLD
  );

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION unicarona.notificar_nova_mensagem()
  FROM PUBLIC;

DROP TRIGGER IF EXISTS notificar_nova_mensagem
  ON unicarona.mensagens;

CREATE TRIGGER notificar_nova_mensagem
  AFTER INSERT ON unicarona.mensagens
  FOR EACH ROW
  EXECUTE FUNCTION unicarona.notificar_nova_mensagem();


REVOKE ALL ON unicarona.conversas, unicarona.mensagens
  FROM PUBLIC, anon, authenticated;

REVOKE ALL ON SEQUENCE unicarona.conversas_id_conversa_seq,
  unicarona.mensagens_id_mensagem_seq
  FROM PUBLIC, anon, authenticated;

GRANT USAGE ON SCHEMA unicarona TO authenticated;

COMMIT;
