-- Executar na conexao PostgreSQL do projeto, com o schema unicarona existente.
-- Apenas estrutura: nao cria cobrancas nem altera solicitacoes ou vagas.
BEGIN;

CREATE TABLE IF NOT EXISTS unicarona.pagamentos (
  id_pagamento INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_solicitacao INTEGER NOT NULL,
  referencia UUID NOT NULL,
  provedor VARCHAR(30) NOT NULL DEFAULT 'ABACATEPAY',
  modo_teste BOOLEAN NOT NULL DEFAULT TRUE,
  metodo VARCHAR(10) NOT NULL DEFAULT 'PIX',
  valor_centavos BIGINT NOT NULL,
  status_criacao VARCHAR(20) NOT NULL DEFAULT 'PREPARADA',
  id_provedor VARCHAR(100),
  status_provedor VARCHAR(30),
  pix_copia_e_cola TEXT,
  qr_code_base64 TEXT,
  expira_em TIMESTAMPTZ,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pagamentos_pkey PRIMARY KEY (id_pagamento),
  CONSTRAINT uq_pagamentos_referencia UNIQUE (referencia),
  CONSTRAINT uq_pagamentos_provedor_id
    UNIQUE (provedor, modo_teste, id_provedor),
  CONSTRAINT fk_pagamentos_solicitacao
    FOREIGN KEY (id_solicitacao)
    REFERENCES unicarona.solicitacoes(id_solicitacao)
    ON DELETE RESTRICT,
  CONSTRAINT chk_pagamentos_provedor CHECK (provedor = 'ABACATEPAY'),
  CONSTRAINT chk_pagamentos_metodo CHECK (metodo = 'PIX'),
  -- Mesmo limite de NUMERIC(10, 2) das caronas, representado em centavos.
  CONSTRAINT chk_pagamentos_valor
    CHECK (valor_centavos BETWEEN 1 AND 9999999999),
  CONSTRAINT chk_pagamentos_status_criacao
    CHECK (status_criacao IN ('PREPARADA', 'CONFIRMADA', 'INCERTA', 'FALHOU')),
  CONSTRAINT chk_pagamentos_id_provedor
    CHECK (id_provedor IS NULL OR LENGTH(BTRIM(id_provedor)) > 0),
  CONSTRAINT chk_pagamentos_status_provedor
    CHECK (status_provedor IS NULL OR status_provedor IN (
      'PENDING', 'EXPIRED', 'CANCELLED', 'PAID', 'UNDER_DISPUTE',
      'REFUNDED', 'REDEEMED', 'APPROVED', 'FAILED'
    )),
  CONSTRAINT chk_pagamentos_criacao_confirmada
    CHECK (status_criacao <> 'CONFIRMADA' OR (
      id_provedor IS NOT NULL AND status_provedor IS NOT NULL
    ))
);

CREATE INDEX IF NOT EXISTS idx_pagamentos_solicitacao_criado_em
  ON unicarona.pagamentos (id_solicitacao, criado_em);

-- Sem politicas para clientes: acesso pelo backend com a role do banco.
ALTER TABLE unicarona.pagamentos ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON unicarona.pagamentos FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE unicarona.pagamentos_id_pagamento_seq
  FROM PUBLIC, anon, authenticated;

COMMIT;
