BEGIN;

CREATE SCHEMA IF NOT EXISTS unicarona;

CREATE TABLE IF NOT EXISTS unicarona.instituicoes (
  id_instituicao INTEGER GENERATED BY DEFAULT AS IDENTITY,
  codigo_emec INTEGER NOT NULL,
  nome VARCHAR(255) NOT NULL,
  sigla VARCHAR(50),
  municipio VARCHAR(100) NOT NULL,
  uf CHAR(2) NOT NULL,
  ativa BOOLEAN NOT NULL DEFAULT TRUE,

  CONSTRAINT instituicoes_pkey PRIMARY KEY (id_instituicao),
  CONSTRAINT instituicoes_codigo_emec_key UNIQUE (codigo_emec)
);

CREATE INDEX IF NOT EXISTS idx_instituicoes_nome
  ON unicarona.instituicoes (nome);

CREATE INDEX IF NOT EXISTS idx_instituicoes_sigla
  ON unicarona.instituicoes (sigla);

CREATE TABLE IF NOT EXISTS unicarona.instituicoes_campi (
  id_campus INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_instituicao INTEGER NOT NULL,
  nome VARCHAR(150) NOT NULL,
  municipio VARCHAR(100) NOT NULL,
  uf CHAR(2) NOT NULL,
  latitude NUMERIC(10, 8),
  longitude NUMERIC(11, 8),
  ativo BOOLEAN NOT NULL DEFAULT TRUE,

  CONSTRAINT instituicoes_campi_pkey PRIMARY KEY (id_campus),
  CONSTRAINT uq_campus_instituicao_municipio
    UNIQUE (id_instituicao, nome, municipio, uf),
  CONSTRAINT fk_campi_instituicoes
    FOREIGN KEY (id_instituicao)
    REFERENCES unicarona.instituicoes(id_instituicao)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS unicarona.usuarios (
  id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  email_verificado BOOLEAN NOT NULL DEFAULT FALSE,
  codigo_verificacao_email VARCHAR(255),
  codigo_verificacao_email_expira_em TIMESTAMPTZ,
  codigo_verificacao_email_enviado_em TIMESTAMPTZ,
  codigo_redefinicao_senha VARCHAR(255),
  codigo_redefinicao_senha_expira_em TIMESTAMPTZ,
  codigo_redefinicao_senha_enviado_em TIMESTAMPTZ,
  id_instituicao INTEGER,
  instituicao VARCHAR(255),
  campus VARCHAR(150),
  foto_perfil VARCHAR(500),
  tipo_perfil VARCHAR(20) NOT NULL DEFAULT 'PASSAGEIRO',
  tipo_perfil_solicitado VARCHAR(20),
  status_verificacao VARCHAR(20) NOT NULL DEFAULT 'NAO_ENVIADO',
  documento_verificacao VARCHAR(255),
  senha VARCHAR(255) NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario),
  CONSTRAINT fk_usuarios_instituicoes
    FOREIGN KEY (id_instituicao)
    REFERENCES unicarona.instituicoes(id_instituicao)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_usuarios_email_normalizado
  ON unicarona.usuarios (LOWER(email));

CREATE INDEX IF NOT EXISTS idx_usuarios_instituicao
  ON unicarona.usuarios (id_instituicao);

CREATE TABLE IF NOT EXISTS unicarona.caronas (
  id_carona INTEGER GENERATED BY DEFAULT AS IDENTITY,
  origem VARCHAR(255) NOT NULL,
  origem_cidade VARCHAR(100),
  origem_latitude NUMERIC(10, 8),
  origem_longitude NUMERIC(11, 8),
  destino VARCHAR(255) NOT NULL,
  destino_cidade VARCHAR(100),
  destino_latitude NUMERIC(10, 8),
  destino_longitude NUMERIC(11, 8),
  data_inicio DATE NOT NULL,
  data_fim DATE,
  horario TIME NOT NULL,
  vagas INTEGER NOT NULL,
  valor NUMERIC(10, 2) NOT NULL,
  recorrente BOOLEAN NOT NULL DEFAULT FALSE,
  dias_semana JSONB,
  observacoes TEXT,
  status VARCHAR(30) NOT NULL DEFAULT 'ATIVA',
  id_usuario INTEGER NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT caronas_pkey PRIMARY KEY (id_carona),
  CONSTRAINT chk_caronas_vagas CHECK (vagas >= 0 AND vagas <= 4),
  CONSTRAINT chk_caronas_valor CHECK (valor >= 0),
  CONSTRAINT fk_caronas_usuarios
    FOREIGN KEY (id_usuario)
    REFERENCES unicarona.usuarios(id_usuario)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_caronas_usuario
  ON unicarona.caronas (id_usuario);

CREATE INDEX IF NOT EXISTS idx_caronas_status_data_horario
  ON unicarona.caronas (status, data_inicio, horario);

CREATE TABLE IF NOT EXISTS unicarona.pontos_embarque (
  id_ponto_embarque INTEGER GENERATED BY DEFAULT AS IDENTITY,
  nome VARCHAR(100),
  endereco VARCHAR(255) NOT NULL,
  latitude NUMERIC(10, 8) NOT NULL,
  longitude NUMERIC(11, 8) NOT NULL,
  ordem INTEGER NOT NULL DEFAULT 1,
  id_carona INTEGER NOT NULL,

  CONSTRAINT pontos_embarque_pkey PRIMARY KEY (id_ponto_embarque),
  CONSTRAINT chk_pontos_embarque_ordem CHECK (ordem >= 1),
  CONSTRAINT fk_pontos_embarque_carona
    FOREIGN KEY (id_carona)
    REFERENCES unicarona.caronas(id_carona)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_pontos_embarque_carona
  ON unicarona.pontos_embarque (id_carona);

CREATE TABLE IF NOT EXISTS unicarona.solicitacoes (
  id_solicitacao INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_carona INTEGER NOT NULL,
  id_passageiro INTEGER NOT NULL,
  id_ponto_embarque INTEGER,
  tipo_ponto_embarque VARCHAR(30) NOT NULL DEFAULT 'EXISTENTE',
  local_embarque VARCHAR(255) NOT NULL,
  embarque_latitude NUMERIC(10, 8) NOT NULL,
  embarque_longitude NUMERIC(11, 8) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'PENDENTE',
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT solicitacoes_pkey PRIMARY KEY (id_solicitacao),
  CONSTRAINT uq_solicitacao_carona_passageiro
    UNIQUE (id_carona, id_passageiro),
  CONSTRAINT fk_solicitacoes_caronas
    FOREIGN KEY (id_carona)
    REFERENCES unicarona.caronas(id_carona)
    ON DELETE RESTRICT,
  CONSTRAINT fk_solicitacoes_usuarios
    FOREIGN KEY (id_passageiro)
    REFERENCES unicarona.usuarios(id_usuario)
    ON DELETE RESTRICT,
  CONSTRAINT fk_solicitacoes_pontos_embarque
    FOREIGN KEY (id_ponto_embarque)
    REFERENCES unicarona.pontos_embarque(id_ponto_embarque)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_solicitacoes_passageiro
  ON unicarona.solicitacoes (id_passageiro);

CREATE INDEX IF NOT EXISTS idx_solicitacoes_ponto_embarque
  ON unicarona.solicitacoes (id_ponto_embarque);

CREATE INDEX IF NOT EXISTS idx_solicitacoes_status
  ON unicarona.solicitacoes (status);

CREATE TABLE IF NOT EXISTS unicarona.veiculos (
  id_veiculo INTEGER GENERATED BY DEFAULT AS IDENTITY,
  modelo VARCHAR(100) NOT NULL,
  cor VARCHAR(50) NOT NULL,
  placa VARCHAR(10) NOT NULL,
  id_usuario INTEGER NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT veiculos_pkey PRIMARY KEY (id_veiculo),
  CONSTRAINT uq_veiculos_usuario UNIQUE (id_usuario),
  CONSTRAINT fk_veiculos_usuarios
    FOREIGN KEY (id_usuario)
    REFERENCES unicarona.usuarios(id_usuario)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_veiculos_placa_normalizada
  ON unicarona.veiculos (UPPER(placa));

CREATE TABLE IF NOT EXISTS unicarona.avaliacoes (
  id_avaliacao INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_solicitacao INTEGER NOT NULL,
  id_avaliador INTEGER NOT NULL,
  id_avaliado INTEGER NOT NULL,
  nota SMALLINT NOT NULL,
  comentario VARCHAR(500),
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT avaliacoes_pkey PRIMARY KEY (id_avaliacao),
  CONSTRAINT uq_avaliacao_solicitacao_avaliador
    UNIQUE (id_solicitacao, id_avaliador),
  CONSTRAINT chk_avaliacoes_nota CHECK (nota >= 1 AND nota <= 5),
  CONSTRAINT fk_avaliacoes_solicitacao
    FOREIGN KEY (id_solicitacao)
    REFERENCES unicarona.solicitacoes(id_solicitacao)
    ON DELETE RESTRICT,
  CONSTRAINT fk_avaliacoes_avaliador
    FOREIGN KEY (id_avaliador)
    REFERENCES unicarona.usuarios(id_usuario)
    ON DELETE RESTRICT,
  CONSTRAINT fk_avaliacoes_avaliado
    FOREIGN KEY (id_avaliado)
    REFERENCES unicarona.usuarios(id_usuario)
    ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_avaliacoes_avaliado
  ON unicarona.avaliacoes (id_avaliado);

-- Somente o backend acessa as tabelas diretamente.
REVOKE ALL ON SCHEMA unicarona FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL TABLES IN SCHEMA unicarona
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA unicarona
  FROM PUBLIC, anon, authenticated;

ALTER DEFAULT PRIVILEGES IN SCHEMA unicarona
  REVOKE ALL ON TABLES FROM anon, authenticated;

ALTER DEFAULT PRIVILEGES IN SCHEMA unicarona
  REVOKE ALL ON SEQUENCES FROM anon, authenticated;

COMMIT;
