BEGIN;

CREATE SCHEMA IF NOT EXISTS unicarona;

CREATE TABLE IF NOT EXISTS unicarona.instituicoes (
  id_instituicao INTEGER GENERATED BY DEFAULT AS IDENTITY,
  codigo_emec INTEGER NOT NULL,
  nome VARCHAR(255) NOT NULL,
  sigla VARCHAR(50),
  municipio VARCHAR(100) NOT NULL,
  uf CHAR(2) NOT NULL,
  ativa BOOLEAN NOT NULL DEFAULT TRUE,

  CONSTRAINT instituicoes_pkey PRIMARY KEY (id_instituicao),
  CONSTRAINT instituicoes_codigo_emec_key UNIQUE (codigo_emec)
);

CREATE INDEX IF NOT EXISTS idx_instituicoes_nome
  ON unicarona.instituicoes (nome);

CREATE INDEX IF NOT EXISTS idx_instituicoes_sigla
  ON unicarona.instituicoes (sigla);

CREATE TABLE IF NOT EXISTS unicarona.instituicoes_campi (
  id_campus INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_instituicao INTEGER NOT NULL,
  nome VARCHAR(150) NOT NULL,
  municipio VARCHAR(100) NOT NULL,
  uf CHAR(2) NOT NULL,
  latitude NUMERIC(10, 8),
  longitude NUMERIC(11, 8),
  ativo BOOLEAN NOT NULL DEFAULT TRUE,

  CONSTRAINT instituicoes_campi_pkey PRIMARY KEY (id_campus),
  CONSTRAINT uq_campus_instituicao_municipio
    UNIQUE (id_instituicao, nome, municipio, uf),
  CONSTRAINT fk_campi_instituicoes
    FOREIGN KEY (id_instituicao)
    REFERENCES unicarona.instituicoes(id_instituicao)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS unicarona.usuarios (
  id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY,
  auth_id UUID,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  id_instituicao INTEGER,
  instituicao VARCHAR(255),
  campus VARCHAR(150),
  foto_perfil VARCHAR(500),
  tipo_perfil VARCHAR(20) NOT NULL DEFAULT 'PASSAGEIRO',
  tipo_perfil_solicitado VARCHAR(20),
  status_verificacao VARCHAR(20) NOT NULL DEFAULT 'NAO_ENVIADO',
  documento_verificacao VARCHAR(255),
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario),
  CONSTRAINT usuarios_auth_id_key UNIQUE (auth_id),
  CONSTRAINT fk_usuarios_auth
    FOREIGN KEY (auth_id)
    REFERENCES auth.users(id)
    ON DELETE RESTRICT,
  CONSTRAINT fk_usuarios_instituicoes
    FOREIGN KEY (id_instituicao)
    REFERENCES unicarona.instituicoes(id_instituicao)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_usuarios_email_normalizado
  ON unicarona.usuarios (LOWER(email));

CREATE INDEX IF NOT EXISTS idx_usuarios_instituicao
  ON unicarona.usuarios (id_instituicao);

CREATE OR REPLACE FUNCTION unicarona.criar_perfil_usuario()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  IF NEW.email IS NULL THEN
    RETURN NEW;
  END IF;

  UPDATE unicarona.usuarios
  SET auth_id = NEW.id
  WHERE LOWER(email) = LOWER(NEW.email)
    AND auth_id IS NULL;

  IF FOUND THEN
    RETURN NEW;
  END IF;

  INSERT INTO unicarona.usuarios (auth_id, nome, email)
  VALUES (
    NEW.id,
    COALESCE(
      NULLIF(BTRIM(NEW.raw_user_meta_data ->> 'nome'), ''),
      SPLIT_PART(NEW.email, '@', 1)
    ),
    LOWER(NEW.email)
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS criar_perfil_apos_cadastro ON auth.users;

CREATE TRIGGER criar_perfil_apos_cadastro
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION unicarona.criar_perfil_usuario();

CREATE TABLE IF NOT EXISTS unicarona.caronas (
  id_carona INTEGER GENERATED BY DEFAULT AS IDENTITY,
  origem VARCHAR(255) NOT NULL,
  origem_cidade VARCHAR(100),
  origem_latitude NUMERIC(10, 8),
  origem_longitude NUMERIC(11, 8),
  destino VARCHAR(255) NOT NULL,
  destino_cidade VARCHAR(100),
  destino_latitude NUMERIC(10, 8),
  destino_longitude NUMERIC(11, 8),
  data_inicio DATE NOT NULL,
  data_fim DATE,
  horario TIME NOT NULL,
  vagas INTEGER NOT NULL,
  valor NUMERIC(10, 2) NOT NULL,
  recorrente BOOLEAN NOT NULL DEFAULT FALSE,
  dias_semana JSONB,
  observacoes TEXT,
  status VARCHAR(30) NOT NULL DEFAULT 'ATIVA',
  id_usuario INTEGER NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT caronas_pkey PRIMARY KEY (id_carona),
  CONSTRAINT chk_caronas_vagas CHECK (vagas >= 0 AND vagas <= 4),
  CONSTRAINT chk_caronas_valor CHECK (valor >= 0),
  CONSTRAINT fk_caronas_usuarios
    FOREIGN KEY (id_usuario)
    REFERENCES unicarona.usuarios(id_usuario)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_caronas_usuario
  ON unicarona.caronas (id_usuario);

CREATE INDEX IF NOT EXISTS idx_caronas_status_data_horario
  ON unicarona.caronas (status, data_inicio, horario);

CREATE TABLE IF NOT EXISTS unicarona.pontos_embarque (
  id_ponto_embarque INTEGER GENERATED BY DEFAULT AS IDENTITY,
  nome VARCHAR(100),
  endereco VARCHAR(255) NOT NULL,
  latitude NUMERIC(10, 8) NOT NULL,
  longitude NUMERIC(11, 8) NOT NULL,
  ordem INTEGER NOT NULL DEFAULT 1,
  id_carona INTEGER NOT NULL,

  CONSTRAINT pontos_embarque_pkey PRIMARY KEY (id_ponto_embarque),
  CONSTRAINT chk_pontos_embarque_ordem CHECK (ordem >= 1),
  CONSTRAINT fk_pontos_embarque_carona
    FOREIGN KEY (id_carona)
    REFERENCES unicarona.caronas(id_carona)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_pontos_embarque_carona
  ON unicarona.pontos_embarque (id_carona);

CREATE TABLE IF NOT EXISTS unicarona.solicitacoes (
  id_solicitacao INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_carona INTEGER NOT NULL,
  id_passageiro INTEGER NOT NULL,
  id_ponto_embarque INTEGER,
  tipo_ponto_embarque VARCHAR(30) NOT NULL DEFAULT 'EXISTENTE',
  local_embarque VARCHAR(255) NOT NULL,
  embarque_latitude NUMERIC(10, 8) NOT NULL,
  embarque_longitude NUMERIC(11, 8) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'PENDENTE',
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT solicitacoes_pkey PRIMARY KEY (id_solicitacao),
  CONSTRAINT uq_solicitacao_carona_passageiro
    UNIQUE (id_carona, id_passageiro),
  CONSTRAINT fk_solicitacoes_caronas
    FOREIGN KEY (id_carona)
    REFERENCES unicarona.caronas(id_carona)
    ON DELETE RESTRICT,
  CONSTRAINT fk_solicitacoes_usuarios
    FOREIGN KEY (id_passageiro)
    REFERENCES unicarona.usuarios(id_usuario)
    ON DELETE RESTRICT,
  CONSTRAINT fk_solicitacoes_pontos_embarque
    FOREIGN KEY (id_ponto_embarque)
    REFERENCES unicarona.pontos_embarque(id_ponto_embarque)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_solicitacoes_passageiro
  ON unicarona.solicitacoes (id_passageiro);

CREATE INDEX IF NOT EXISTS idx_solicitacoes_ponto_embarque
  ON unicarona.solicitacoes (id_ponto_embarque);

CREATE INDEX IF NOT EXISTS idx_solicitacoes_status
  ON unicarona.solicitacoes (status);

CREATE TABLE IF NOT EXISTS unicarona.pagamentos (
  id_pagamento INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_solicitacao INTEGER NOT NULL,
  referencia UUID NOT NULL,
  provedor VARCHAR(30) NOT NULL DEFAULT 'ABACATEPAY',
  modo_teste BOOLEAN NOT NULL DEFAULT TRUE,
  metodo VARCHAR(10) NOT NULL DEFAULT 'PIX',
  valor_centavos BIGINT NOT NULL,
  status_criacao VARCHAR(20) NOT NULL DEFAULT 'PREPARADA',
  id_provedor VARCHAR(100),
  status_provedor VARCHAR(30),
  pix_copia_e_cola TEXT,
  qr_code_base64 TEXT,
  expira_em TIMESTAMPTZ,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pagamentos_pkey PRIMARY KEY (id_pagamento),
  CONSTRAINT uq_pagamentos_referencia UNIQUE (referencia),
  CONSTRAINT uq_pagamentos_provedor_id
    UNIQUE (provedor, modo_teste, id_provedor),
  CONSTRAINT fk_pagamentos_solicitacao
    FOREIGN KEY (id_solicitacao)
    REFERENCES unicarona.solicitacoes(id_solicitacao)
    ON DELETE RESTRICT,
  CONSTRAINT chk_pagamentos_provedor CHECK (provedor = 'ABACATEPAY'),
  CONSTRAINT chk_pagamentos_metodo CHECK (metodo = 'PIX'),
  -- Mesmo limite de NUMERIC(10, 2) das caronas, representado em centavos.
  CONSTRAINT chk_pagamentos_valor
    CHECK (valor_centavos BETWEEN 1 AND 9999999999),
  CONSTRAINT chk_pagamentos_status_criacao
    CHECK (status_criacao IN ('PREPARADA', 'CONFIRMADA', 'INCERTA', 'FALHOU')),
  CONSTRAINT chk_pagamentos_id_provedor
    CHECK (id_provedor IS NULL OR LENGTH(BTRIM(id_provedor)) > 0),
  CONSTRAINT chk_pagamentos_status_provedor
    CHECK (status_provedor IS NULL OR status_provedor IN (
      'PENDING', 'EXPIRED', 'CANCELLED', 'PAID', 'UNDER_DISPUTE',
      'REFUNDED', 'REDEEMED', 'APPROVED', 'FAILED'
    )),
  CONSTRAINT chk_pagamentos_criacao_confirmada
    CHECK (status_criacao <> 'CONFIRMADA' OR (
      id_provedor IS NOT NULL AND status_provedor IS NOT NULL
    ))
);

CREATE INDEX IF NOT EXISTS idx_pagamentos_solicitacao_criado_em
  ON unicarona.pagamentos (id_solicitacao, criado_em);

-- Sem politicas para clientes: acesso pelo backend com a role do banco.
ALTER TABLE unicarona.pagamentos ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON unicarona.pagamentos FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE unicarona.pagamentos_id_pagamento_seq
  FROM PUBLIC, anon, authenticated;

CREATE TABLE IF NOT EXISTS unicarona.pagamentos_eventos_webhook (
  id_evento VARCHAR(100) NOT NULL,
  id_pagamento INTEGER NOT NULL,
  tipo VARCHAR(50) NOT NULL,
  processado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pagamentos_eventos_webhook_pkey PRIMARY KEY (id_evento),
  CONSTRAINT fk_pagamentos_eventos_webhook_pagamento
    FOREIGN KEY (id_pagamento)
    REFERENCES unicarona.pagamentos(id_pagamento)
    ON DELETE RESTRICT,
  CONSTRAINT chk_pagamentos_eventos_webhook_id
    CHECK (LENGTH(BTRIM(id_evento)) BETWEEN 1 AND 100),
  CONSTRAINT chk_pagamentos_eventos_webhook_tipo
    CHECK (LENGTH(BTRIM(tipo)) BETWEEN 1 AND 50)
);

CREATE INDEX IF NOT EXISTS idx_pagamentos_eventos_webhook_pagamento
  ON unicarona.pagamentos_eventos_webhook (id_pagamento, processado_em);

ALTER TABLE unicarona.pagamentos_eventos_webhook ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON unicarona.pagamentos_eventos_webhook
  FROM PUBLIC, anon, authenticated;

CREATE TABLE IF NOT EXISTS unicarona.veiculos (
  id_veiculo INTEGER GENERATED BY DEFAULT AS IDENTITY,
  modelo VARCHAR(100) NOT NULL,
  cor VARCHAR(50) NOT NULL,
  placa VARCHAR(10) NOT NULL,
  id_usuario INTEGER NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT veiculos_pkey PRIMARY KEY (id_veiculo),
  CONSTRAINT uq_veiculos_usuario UNIQUE (id_usuario),
  CONSTRAINT fk_veiculos_usuarios
    FOREIGN KEY (id_usuario)
    REFERENCES unicarona.usuarios(id_usuario)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_veiculos_placa_normalizada
  ON unicarona.veiculos (UPPER(placa));

CREATE TABLE IF NOT EXISTS unicarona.avaliacoes (
  id_avaliacao INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_solicitacao INTEGER NOT NULL,
  id_avaliador INTEGER NOT NULL,
  id_avaliado INTEGER NOT NULL,
  nota SMALLINT NOT NULL,
  comentario VARCHAR(500),
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT avaliacoes_pkey PRIMARY KEY (id_avaliacao),
  CONSTRAINT uq_avaliacao_solicitacao_avaliador
    UNIQUE (id_solicitacao, id_avaliador),
  CONSTRAINT chk_avaliacoes_nota CHECK (nota >= 1 AND nota <= 5),
  CONSTRAINT fk_avaliacoes_solicitacao
    FOREIGN KEY (id_solicitacao)
    REFERENCES unicarona.solicitacoes(id_solicitacao)
    ON DELETE RESTRICT,
  CONSTRAINT fk_avaliacoes_avaliador
    FOREIGN KEY (id_avaliador)
    REFERENCES unicarona.usuarios(id_usuario)
    ON DELETE RESTRICT,
  CONSTRAINT fk_avaliacoes_avaliado
    FOREIGN KEY (id_avaliado)
    REFERENCES unicarona.usuarios(id_usuario)
    ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_avaliacoes_avaliado
  ON unicarona.avaliacoes (id_avaliado);

CREATE TABLE IF NOT EXISTS unicarona.conversas (
  id_conversa INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_solicitacao INTEGER NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT conversas_pkey PRIMARY KEY (id_conversa),
  CONSTRAINT uq_conversas_solicitacao UNIQUE (id_solicitacao),
  CONSTRAINT fk_conversas_solicitacoes
    FOREIGN KEY (id_solicitacao)
    REFERENCES unicarona.solicitacoes(id_solicitacao)
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS unicarona.mensagens (
  id_mensagem INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_conversa INTEGER NOT NULL,
  id_remetente INTEGER NOT NULL,
  conteudo VARCHAR(1000) NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT mensagens_pkey PRIMARY KEY (id_mensagem),
  CONSTRAINT chk_mensagens_conteudo
    CHECK (LENGTH(BTRIM(conteudo)) BETWEEN 1 AND 1000),
  CONSTRAINT fk_mensagens_conversas
    FOREIGN KEY (id_conversa)
    REFERENCES unicarona.conversas(id_conversa)
    ON DELETE RESTRICT,
  CONSTRAINT fk_mensagens_remetente
    FOREIGN KEY (id_remetente)
    REFERENCES unicarona.usuarios(id_usuario)
    ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_mensagens_conversa_criado_em
  ON unicarona.mensagens (id_conversa, criado_em);

CREATE OR REPLACE FUNCTION unicarona.usuario_participa_conversa(topico TEXT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM unicarona.conversas conversa
    INNER JOIN unicarona.solicitacoes solicitacao
      ON solicitacao.id_solicitacao = conversa.id_solicitacao
    INNER JOIN unicarona.caronas carona
      ON carona.id_carona = solicitacao.id_carona
    INNER JOIN unicarona.usuarios passageiro
      ON passageiro.id_usuario = solicitacao.id_passageiro
    INNER JOIN unicarona.usuarios motorista
      ON motorista.id_usuario = carona.id_usuario
    WHERE topico = 'conversa:' || conversa.id_conversa::TEXT
      AND (
        passageiro.auth_id = (SELECT auth.uid())
        OR motorista.auth_id = (SELECT auth.uid())
      )
  );
$$;

REVOKE ALL ON FUNCTION unicarona.usuario_participa_conversa(TEXT)
  FROM PUBLIC;
GRANT EXECUTE ON FUNCTION unicarona.usuario_participa_conversa(TEXT)
  TO authenticated;

DROP POLICY IF EXISTS chat_participantes_recebem_mensagens
  ON realtime.messages;

CREATE POLICY chat_participantes_recebem_mensagens
  ON realtime.messages
  FOR SELECT
  TO authenticated
  USING (
    realtime.messages.extension = 'broadcast'
    AND unicarona.usuario_participa_conversa(
      (SELECT realtime.topic())
    )
  );

CREATE OR REPLACE FUNCTION unicarona.notificar_nova_mensagem()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  PERFORM realtime.broadcast_changes(
    'conversa:' || NEW.id_conversa::TEXT,
    TG_OP,
    TG_OP,
    TG_TABLE_NAME,
    TG_TABLE_SCHEMA,
    NEW,
    OLD
  );

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION unicarona.notificar_nova_mensagem()
  FROM PUBLIC;

DROP TRIGGER IF EXISTS notificar_nova_mensagem
  ON unicarona.mensagens;

CREATE TRIGGER notificar_nova_mensagem
  AFTER INSERT ON unicarona.mensagens
  FOR EACH ROW
  EXECUTE FUNCTION unicarona.notificar_nova_mensagem();


-- Somente o backend acessa as tabelas diretamente.
REVOKE ALL ON SCHEMA unicarona FROM PUBLIC, anon, authenticated;
GRANT USAGE ON SCHEMA unicarona TO authenticated;
REVOKE ALL ON ALL TABLES IN SCHEMA unicarona
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA unicarona
  FROM PUBLIC, anon, authenticated;

ALTER DEFAULT PRIVILEGES IN SCHEMA unicarona
  REVOKE ALL ON TABLES FROM anon, authenticated;

ALTER DEFAULT PRIVILEGES IN SCHEMA unicarona
  REVOKE ALL ON SEQUENCES FROM anon, authenticated;

COMMIT;
